import logging
from typing import Any, Dict, Optional

from src.agents.base_llm_agent import BaseLLMAgent  # Assuming base exists; stub if not

logger = logging.getLogger(__name__)

class ToolGeneratorAgent(BaseLLMAgent):
    """
    Agent for autogenerating dynamic custom tools from descriptions.
    Stubs for now: parses simple desc like "name=swap, desc=swaps elements, params=lst: list, i: int, j: int, returns=None"
    Generates Python def stub with raise NotImplementedError.
    """
    def __init__(self, agent_id: str, message_bus, session_logger, config: Dict[str, Any] = None, **kwargs):
        super().__init__(agent_id=agent_id, message_bus=message_bus, session_logger=session_logger, config=config or {})
        self.tools_registry = {}  # Global registry for generated tools

    async def run(self):
        """Stub run: listens for tool gen requests."""
        logger.info(f"[{self.agent_id}] ToolGenerator started (stub mode)")
        while True:
            msg = await self.message_bus.receive(self.agent_id)
            if msg.message_type == "generate_tool":
                desc = msg.content.get("description", "")
                stub_code = self._generate_stub(desc)
                self.tools_registry[desc.split("name=")[1].split(",")[0]] = stub_code
                response = {"stub_code": stub_code, "registered": True}
                await self.message_bus.send(Message(from_agent=self.agent_id, to_agent=msg.from_agent, content=response))
            await asyncio.sleep(0.1)

    def _generate_stub(self, desc: str) -> str:
        """Simple parser for desc to stub code. Enhance with LLM later."""
        # Stub parser: assume format "name=NAME, desc=..., params=..., returns=..."
        parts = {}
        for part in desc.split(","):
            if "=" in part:
                k, v = part.split("=", 1)
                parts[k.strip()] = v.strip()
        
        name = parts.get("name", "custom_tool")
        doc = parts.get("desc", "Autogenerated tool stub")
        params_str = ", ".join([f"{p.split(':')[0].strip()}: {p.split(':')[1].strip()}" for p in parts.get("params", "").split(",") if p.strip()])
        returns = parts.get("returns", "Any")
        
        stub = f'''def {name}({params_str}) -> {returns}:
    """{doc}"""
    raise NotImplementedError("Autogenerated stub - implement the logic here")
'''
        logger.info(f"Generated stub for {name}")
        return stub

    def register_tool(self, name: str, func_code: str):
        """Register stub in registry for Executor/Actor use."""
        self.tools_registry[name] = func_code
        logger.info(f"Tool {name} registered (stub)")

    def get_tool(self, name: str) -> Optional[str]:
        return self.tools_registry.get(name)