#!/usr/bin/env python3
"""
Grokputer Progress Saver - Auto-backup script generated by MCP-Swarm.
Saves src/, logs/, vault/, outputs/; updates docs (git commit); dumps agent states (JSON/Redis sim).
Invoke anytime for safe sleep—4am friendly!
"""

import shutil
import subprocess
import json
import os
from datetime import datetime
from pathlib import Path

PROGRESS_DIRS = ["src", "logs", "outputs", "mcp", "db"]  # Removed vault (5GB+ user files - backup separately if needed)
DOC_FILES = ["main.py", "COLLABORATION.md", "DEVELOPMENT_PLAN.md"]  # Add more as needed
BACKUP_DIR = Path("backups")
STATES_FILE = BACKUP_DIR / "agent_states.json"

def backup_progress(timestamp):
    """Tar key dirs for full progress save."""
    backup_tar = BACKUP_DIR / f"grokputer_progress_{timestamp}.tar.gz"
    BACKUP_DIR.mkdir(exist_ok=True)

    cmd = ["tar", "-czf", str(backup_tar), *PROGRESS_DIRS]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode == 0:
        file_count = sum(len(list(Path(p).rglob('*'))) for p in PROGRESS_DIRS if os.path.exists(p))
        print(f"[SAVE] Progress backed up to {backup_tar} ({file_count} files)")
    else:
        print(f"[ERROR] Backup failed: {result.stderr}")

def update_docs(timestamp):
    """Git commit docs updates."""
    if not Path(".git").exists():
        print("[SKIP] No git repo—docs not committed.")
        return

    # Add/commit relevant files
    cmd_add = ["git", "add", *DOC_FILES]
    subprocess.run(cmd_add, check=True)

    msg = f"Auto-update docs - {timestamp}"
    cmd_commit = ["git", "commit", "-m", msg]
    result = subprocess.run(cmd_commit, capture_output=True, text=True)
    if result.returncode == 0:
        subprocess.run(["git", "push"], check=True)
        print("[SAVE] Docs updated and pushed to repo.")
    else:
        print(f"[SKIP] No doc changes or commit failed: {result.stderr}")

def save_agent_states(timestamp):
    """Dump agent/KB states to JSON (sim Redis SAVE)."""
    # Sim Redis: Load from db/kb/sessions.json, save to states
    states = {"timestamp": timestamp, "kb_sessions": [], "votes": {}}

    kb_file = Path("db") / "sessions.json"
    if kb_file.exists():
        with open(kb_file) as f:
            states["kb_sessions"] = json.load(f)

    vote_file = Path("db") / "votes.json"
    if vote_file.exists():
        with open(vote_file) as f:
            states["votes"] = json.load(f)

    with open(STATES_FILE, "w") as f:
        json.dump(states, f, indent=2)
    print(f"[SAVE] Agent states dumped to {STATES_FILE} (sim Redis SAVE).")

if __name__ == "__main__":
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    print(f"[GROKPUTER SAVE] Starting progress save at {timestamp}...")

    backup_progress(timestamp)
    update_docs(timestamp)
    save_agent_states(timestamp)

    print("\n[COMPLETE] All progress saved - backups, docs updated, states dumped.")
    print("Goodnight! Sleep well - Grokputer has your back. ZA GROKA.")